apiVersion: apps/v1
kind: Deployment
metadata:
  name: earticle-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: article-api
  template:
    metadata:
      labels:
        app: article-api
    spec:
      containers:
      - name: article-api-container
        image: gcr.io/graphite-scout-381515/article-api:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: article-api-service
spec:
  type: LoadBalancer
  selector:
    app: article-api
  ports:
  - port: 80
    targetPort: 80